setStateBasedEndorsement NOutOf for typescript chaincode
hyperledger/fabric-samples pull request #330
Opened 2020-09-13 07:10 UTC by girigaurav

Signed-off-by: Gaurav Giri <girigaurav@gmail.com>

2020-10-01 16:24 UTC, lehors requested changes
Seems to work fine but I'd like to see a few clarifications and one change to the code.

2020-10-11 04:59 UTC, girigaurav commented on asset-transfer-sbe/chaincode-java/src/main/java/org/hyperledger/fabric/samples/sbe/AssetContract.java
> +        // Optionally, set the endorsement policy of the assetId Key, such that any 1(N) out of the Org's Peer specified can endorse future updates
done

2020-10-11 04:59 UTC, girigaurav commented on asset-transfer-sbe/chaincode-java/src/main/java/org/hyperledger/fabric/samples/sbe/AssetContract.java
> +     * Create the policy such that it requires any N Orgs signature's from all of the principals provided
done

2020-10-11 04:59 UTC, girigaurav commented on asset-transfer-sbe/chaincode-java/src/main/java/org/hyperledger/fabric/samples/sbe/AssetContract.java
>       * @param nOrgs the number of N Org signature's to endorse out of the list of Orgs provided
done

2020-10-11 05:00 UTC, girigaurav commented on asset-transfer-sbe/chaincode-typescript/src/assetContract.ts
>          // Set the endorsement policy of the assetId Key, such that current owner Org Peer is required to endorse future updates
done

2020-10-11 05:00 UTC, girigaurav commented on asset-transfer-sbe/chaincode-typescript/src/assetContract.ts
> +        // Optionally, set the endorsement policy of the assetId Key, such that any 1(N) out of the Org's Peer specified can endorse future updates
done

2020-10-11 05:00 UTC, girigaurav commented on asset-transfer-sbe/chaincode-typescript/src/assetContract.ts
> +    // setStateBasedEndorsement enforces that the owner Org Peers must endorse future update transactions for the specified assetId Key
done

2020-10-11 05:00 UTC, girigaurav commented on asset-transfer-sbe/chaincode-typescript/src/assetContract.ts
> +    // setStateBasedEndorsementNOutOf enforces that any N out of the Org's Peers specified must endorse future update transactions for the specified assetId Key.
done

2020-10-11 05:00 UTC, girigaurav commented on asset-transfer-sbe/chaincode-typescript/src/assetContract.ts
> +        await AssetContract.setStateBasedEndorsement(ctx, asset.ID, [newOwnerOrg]);
done

2020-10-11 05:00 UTC, girigaurav commented on asset-transfer-sbe/chaincode-java/src/main/java/org/hyperledger/fabric/samples/sbe/AssetContract.java
> +        setStateBasedEndorsement(ctx, assetId, new String[]{newOwnerOrg});
done

2020-10-12 14:07 UTC, lehors approved these changes
LGTM. Thanks!

2020-10-12 14:07 UTC, merged