shellcheck fix
hyperledger/fabric-samples pull request #340
Opened 2020-09-19 04:12 UTC by lengyijun

2020-09-22 09:59 UTC, lehors reviewed
Thank you for your contribution but for your PR to be acceptable it must have a sign-off (you can add one with git commit --amend -s).

2020-11-10 14:10 UTC, lehors requested changes
No offense but I honestly don't see much value in this PR. Most of the changes are irrelevant, and one change simply breaks the script.

2020-11-10 14:10 UTC, lehors commented on fabcar/startFabric.sh
> +if [ "$CC_SRC_LANGUAGE" = "go" ] -o [ "$CC_SRC_LANGUAGE" = "golang" ] ; then
This syntax is actually incorrect and fails:
$ ./startFabric.sh 
./startFabric.sh: line 16: [: too many arguments
The following will work:
```suggestion
if [ "$CC_SRC_LANGUAGE" = "go" ] || [ "$CC_SRC_LANGUAGE" = "golang" ] ; then
```

2020-12-17 16:38 UTC, nikhil550 commented
This PR is quite stale so i am going to close.

2020-12-17 16:38 UTC, closed without merging