Add mode specific help text
hyperledger/fabric-samples pull request #344
Opened 2020-10-04 12:03 UTC by nikhil550

Moves the help text to the scriptUtils, and create mode specific help text.

For example:
```
./network.sh deployCC -h
Usage: 
  network.sh deployCC [Flags]

    Flags:
    -c <channel name> - deploy chaincode to channel
    -ccn <name> - the short name of the chaincode to deploy: basic (default),ledger, private, sbe, secured
    -ccl <language> - the programming language of the chaincode to deploy: go (default), java, javascript, typescript
    -ccv <version>  - chaincode version. 1.0 (default)
    -ccs <sequence>  - chaincode definition sequence. Must be an integer, 1 (default), 2, 3, etc
    -ccp <path>  - Optional, path to the chaincode. When provided the -ccn will be used as the deployed name and not the short name of the known chaincodes.
    -ccep <policy>  - Optional, chaincode endorsement policy, using signature policy syntax. The default policy requires an endorsement from Org1 and Org2
    -cccg <collection-config>  - Optional, path to a private data collections configuration file
    -cci <fcn name>  - Optional, chaincode init required function to invoke. When provided this function will be invoked after deployment of the chaincode and will define the chaincode as initialization required.

    -h - print this message

 Possible Mode and flag combinations
   deployCC -ccn -ccl -ccv -ccs -ccp -cci -r -d -verbose

 Examples:
   network.sh deployCC -ccn basic -ccl javascript
   network.sh deployCC -ccn mychaincode -ccp ./user/mychaincode -ccv 1 -ccl javascript
```

Let me know what you think.

Signed-off-by: NIKHIL E GUPTA <ngupta@symbridge.com>

2020-10-05 12:54 UTC, lehors requested changes
I think if we go that way we have to do a bit more. I suggest a few more edits for consistency.

2020-10-06 14:16 UTC, nikhil550 commented on test-network/scriptUtils.sh
> +    println "    -c <channel name> - channel name to use (defaults to \"mychannel\")"
Name of channel name to create (defaults to "mychannel")

2020-10-06 14:16 UTC, nikhil550 commented on test-network/scriptUtils.sh
> +    println "    -c <channel name> - channel name to use (defaults to \"mychannel\")"
Name of channel name to create (defaults to "mychannel")

2020-10-06 14:18 UTC, nikhil550 commented on test-network/scriptUtils.sh
> +    println "    -s <dbtype> - the database backend to use: goleveldb (default) or couchdb"
done.

2020-10-06 14:19 UTC, nikhil550 commented
As suggested by Arnaud, I did some edits to the help text more broadly to clean up the language and the clarity.

I also took the opportunity to remove the "restart" mode, which is not used in any of the tutorials or samples, and does not have a practical use.

2020-10-06 14:23 UTC, nikhil550 commented on test-network/scriptUtils.sh
> +    println "    -i <imagetag> - the tag to be used to launch the network (defaults to \"latest\")"
Updated with clearer language throughout

2020-10-06 15:23 UTC, lehors commented on test-network/scriptUtils.sh
> +    println "    -c <channel name> - channel name to use (defaults to \"mychannel\")"
You have one too many "name" in here.

2020-10-06 15:24 UTC, lehors commented on test-network/scriptUtils.sh
> +    println "    -c <channel name> - channel name to use (defaults to \"mychannel\")"
same here.

2020-10-06 15:27 UTC, lehors commented
> As suggested by Arnaud, I did some edits to the help text more broadly to clean up the language and the clarity.
> 
> I also took the opportunity to remove the "restart" mode, which is not used in any of the tutorials or samples, and does not have a practical use.

Sounds reasonable to me but would be worth adding that to the commit log.
I think restart could be useful if it retained all the arguments but as it is, I agree it's not really useful.

2020-10-06 18:18 UTC, nikhil550 commented on test-network/scriptUtils.sh
> +    println "    -c <channel name> - channel name to use (defaults to \"mychannel\")"
done

2020-10-06 18:18 UTC, nikhil550 commented on test-network/scriptUtils.sh
> +    println "    -c <channel name> - channel name to use (defaults to \"mychannel\")"
done.

2020-10-06 19:49 UTC, lehors approved these changes

2020-10-07 07:02 UTC, denyeart approved these changes

2020-10-07 07:03 UTC, merged