Updates to external chaincode readme
hyperledger/fabric-samples pull request #422
Opened 2021-02-19 20:25 UTC by nikhil550

Some updates to the external chaincode readme for readability and clarity. These updates make it less likely that users will not forget to make the required update the .env file like I did. Also

- updating the name of the new docker compose network
- changing the link to the correct tutorial
- adding the path to the required configuration file
- Letting users know they no longer need mount docker.sock.

Signed-off-by: Nikhil Gupta <ngupta@symbridge.com>

2021-02-20 09:23 UTC, lehors requested changes
One small nit, LGTM otherwise.
Thanks.

2021-02-20 09:23 UTC, lehors commented on asset-transfer-basic/chaincode-external/README.md
> +Now that we have started the chaincode service and deployed it to the channel, we can submit to the transactions as we would a normal chaincode.
```suggestion
Now that we have started the chaincode service and deployed it to the channel, we can submit transactions as we would with a normal chaincode.
```

2021-02-20 13:03 UTC, nikhil550 commented on asset-transfer-basic/chaincode-external/README.md
> +Now that we have started the chaincode service and deployed it to the channel, we can submit to the transactions as we would a normal chaincode.
done.

2021-02-22 01:47 UTC, lehors approved these changes
LGTM

2021-02-22 01:47 UTC, merged