Pipeline changes for Linting
hyperledger/fabric-samples pull request #495
Opened 2021-09-23 15:54 UTC by sapthasurendran

- Removed global install of modules. 
- 
- Project can now chose it’s own linting framework, versions and execution pattern
- 
- Fixed linting errors for chaincode-typescript

2021-09-23 16:09 UTC, sapthasurendran commented
/ci-run

2021-09-23 20:08 UTC, denyeart commented
It's good that  asset-transfer-basic chaincode and application javascript has been updated. But should we update all the javascript assets in fabric-samples to be consistent?

Let's have a javascript expert such as @bestbeforetoday or @mbwhite comment on the actual changes.

2021-09-27 13:52 UTC, sapthasurendran commented
> It's good that asset-transfer-basic chaincode and application javascript has been updated. But should we update all the javascript assets in fabric-samples to be consistent? Based on the new lint error in the checks, I think so.
> 
> Let's have a javascript expert such as @bestbeforetoday or @mbwhite comment on the actual changes.

@bestbeforetoday @mbwhite Could you please confirm on this ?

2021-09-29 17:21 UTC, bestbeforetoday requested changes
I think we should also remove the global install of tslint and eslint in the `ci/azure-pipelines.yml` lint job if it's no longer necessary:
```yaml
      - script: npm install -g typescript eslint tslint
        displayName: Install Javascript Linting Deps
```

2021-09-29 17:21 UTC, bestbeforetoday commented on ci/scripts/lint.sh
> +        npm run lint
It would be good to combine this into a single test with "-javascript" since exactly the same operation should be carried out for both project types

2021-09-30 10:30 UTC, bestbeforetoday approved these changes
👍

2021-10-06 12:33 UTC, merged