Convert comments to tsdoc in REST sample
hyperledger/fabric-samples pull request #606
Opened 2022-01-31 12:48 UTC by jt-nti

Signed-off-by: James Taylor <jamest@uk.ibm.com>

2022-01-31 13:25 UTC, mbwhite submitted a review, later dismissed

2022-01-31 14:14 UTC, lehors requested changes
LGTM but I spotted a repeated word you might as well fix.

2022-01-31 14:14 UTC, lehors commented on asset-transfer-basic/rest-api-typescript/src/errors.ts
>   * Smart contract errors from the the basic asset transfer samples do not use
```suggestion
 * Smart contract errors from the basic asset transfer samples do not use
```

2022-01-31 14:19 UTC, jt-nti commented on asset-transfer-basic/rest-api-typescript/src/errors.ts
>   * Smart contract errors from the the basic asset transfer samples do not use
Aha, thanks, fixed!

2022-02-01 16:12 UTC, lehors approved these changes
LGTM. Thanks!

2022-02-01 16:12 UTC, merged