Update the REST Example
hyperledger/fabric-samples pull request #689
Opened 2022-03-28 12:25 UTC by mbwhite

1. For development purposes CORS can hinder testing examples. Therefore enable CORS if needed, default off
2. The default chaincode use Capitalized JSON Names, whereas for new asset the REST validation didn't.. Adjusted
so it matches the chaincode

Signed-off-by: Matthew B White <whitemat@uk.ibm.com>

2022-03-28 13:42 UTC, jt-nti requested changes
Thanks for the PR- it definitely makes sense for the case to match the contract. I think it also needs fixing for PUT and PATCH though.

2022-03-28 13:42 UTC, jt-nti commented on asset-transfer-basic/rest-api-typescript/package.json
> +    "async-mqtt": "^2.6.2",
I don't think this is required?

2022-03-28 14:44 UTC, mbwhite commented on asset-transfer-basic/rest-api-typescript/src/assets.router.ts
> +  logger.debug(req);
it does get logged, but only in the event of an error.. it doesn't get logged if everything works.
added to see what request was that was coming from CURL that was working... 

I'll remove it

2022-03-28 14:45 UTC, mbwhite commented on asset-transfer-basic/rest-api-typescript/src/server.ts
> +  if (devCorsEnable){
yep as discussed will remove it..

2022-03-29 09:42 UTC, jt-nti commented on asset-transfer-basic/rest-api-typescript/src/__tests__/api.test.ts
> +          wrongidfield: 'asset3',
Aha, I like that, much more obvious!

2022-03-29 13:57 UTC, jt-nti commented on asset-transfer-basic/rest-api-typescript/.gitignore
> +package-lock.json
package-lock.json should not be in .gitignore

2022-03-30 09:22 UTC, mbwhite commented
@hyperledger/fabric-samples-maintainers   could you take a look and merge please?  Thanks

2022-03-30 15:28 UTC, jkneubuh commented
How can I take this PR out for a test drive?

Simple web app adjacent to the REST sample, exposed at a different host name?

2022-03-30 15:46 UTC, mbwhite commented
@jkneubuh by means, though you'll need to provide your own insurance..

The relevant parts ended up being making the JSON structure accepted on 'write' actions the same as on 'read' actions. 

(where we need a canonical model)

2022-03-30 21:00 UTC, jkneubuh commented
Why remove the `devCORS` override?  

I would like to access the REST sample endpoint, running on localhost, from a web app / `XMLHttpRequest` loaded from a different domain.  It's OK if this is restrictive by default - is there another way to enable this via config of the service endpoint / env?

2022-03-31 09:47 UTC, jt-nti commented
Although CORS support of some kind might be nice to have, the REST sample was not intended to get into all the various options available for running a REST server. After a bit of discussion the CORS change was removed from this PR because it wasn't related to the other changes.

I'm not fundamentally opposed to adding additional configuration options for scenarios that support the intent to show a production-like sample, however I am slightly nervous about adding too many variations when the sample is arguably already too complex.

2022-03-31 12:19 UTC, jkneubuh approved these changes
This PR Looks OK.

I Preferred The Normal, CamelCase Capitalization Scheme for JSON.

However... Consistency With The Underlying Contract Structures Is Important, Too.

Looks Good.  Ship It.

2022-03-31 12:19 UTC, merged